# permissions for end users to view Generators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: Generator-viewer-role
rules:
- apiGroups:
  - managed.openshift.io
  resources:
  - Generators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - managed.openshift.io
  resources:
  - Generators/status
  verbs:
  - get
