# permissions for end users to view proxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-viewer-role
rules:
- apiGroups:
  - managed.openshift.io
  resources:
  - proxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - managed.openshift.io
  resources:
  - proxies/status
  verbs:
  - get
