
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - managed.openshift.io
  resources:
  - Generators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed.openshift.io
  resources:
  - Generators/finalizers
  verbs:
  - update
- apiGroups:
  - managed.openshift.io
  resources:
  - Generators/status
  verbs:
  - get
  - patch
  - update
